### ISSUE TITLE
ChangeSensitivity or similar function missing from OptionsManager singleton

### ISSUE THREAD

**Issue by NAkbulut** [DarkOceanInteractive/project-wendigo#42]
Feature request
---

**Related problem to feature request**

Missing a `ChangeSensitivity` or similar function on the `OptionsManager` singleton.

**Solution or enhancement to problem**

Add a `ChangeSensitivity` or similar function on the `OptionsManager` singleton, which allows differentiation between the two look-axis. This function may then be called from anywhere within the `ProjectWendigo` namespace.

**Dependencies to the feature request**

In order to use the above solution to this feature request, the `OptionsManager` singleton must be existing.

**Additional context**

``` c#
this.gameObject.GetComponent<CinemachineVirtualCamera>().GetCinemachineComponent<CinemachinePOV>().m_VerticalAxis.m_MaxSpeed = sensitivity;
this.gameObject.GetComponent<CinemachineVirtualCamera>().GetCinemachineComponent<CinemachinePOV>().m_HorizontalAxis.m_MaxSpeed = sensitivity;
```

**Comment by adrienlucbert** [comment]
Dependencies are met now that #39 has been merged.

**Comment by NAkbulut** [comment]
Blocked by #52.
