### ISSUE TITLE
Notebook only adds Item if Notebook opened before

### ISSUE THREAD

**Issue by NAkbulut** [DarkOceanInteractive/project-wendigo#48]
Bug report
---

**Related problem to feature request**

Notebook archival entries only get added if the notebook has been opened at least once before the entry has been added. If the notebook hasn't been opened before trying to add an item to it, then it will not add these items. Once the notebook has been opened once, it will only start adding new items from that point forward.

**Dependencies to the feature request**

This issue has only been tested within the scope of the `IntroLevel` scene, using `AddArchiveEntryById`.

**Comment by adrienlucbert** [comment]
When you open the notebook, it loads its entries from the player's local save.
You need to save the player's data when adding stuff to the notebook.
```csharp
Singletons.Main.Save.Save()
```
I could change it so it's easier to use.
