### ISSUE TITLE
Add option to Open Notebook on different page

### ISSUE THREAD

**Issue by NAkbulut** [DarkOceanInteractive/project-wendigo#49]
Feature request
---

**Related problem to feature request**

When using `Singletons.Main.Notebook.Open()`, it defaults to opening the Journal. There is currently no option to open a specific page, such as the Archive page.

**Solution or enhancement to problem**

Add an optional parameter to `Open`, which allows for a page selection.

**Dependencies to the feature request**

None.

**Comment by adrienlucbert** [comment]
There **is** an option:
```csharp
Singletons.Main.Notebook.ToggleSection(sectionName)
// sectionName can be: "Sections/Journal", "Sections/Maps", "Sections/Archive"
```
https://github.com/DarkOceanInteractive/project-wendigo/blob/develop/Assets/Scripts/Singletons/NotebookManager.cs#L44
